[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "lgtmeow"
description = "LGTMeow 🐾 —— 「本喵觉得很不错～」"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Nyakku Shigure", email = "sigure.qaq@gmail.com" }]
keywords = ["LGTM", "meow", "LGTMeow", "cli", "emoji-kitchen"]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
bindings = "bin"
features = ["copy"]
