name: Test

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update rust toolchain
        run: rustup update
      - uses: actions/cache@v4
        id: cargo-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose
      - name: E2E test
        run: |
          cargo run --release -- setup --default
          cargo run --release -- -r
