name: Test

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-build:
    name: Run pre-build hook
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
      # - name: Install just
      #   uses: extractions/setup-just@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Run pre-build hook
      #   run: just pre-build
      - name: Upload prepared kitchen data
        uses: ./.github/workflows/pre-build.yml

  run-test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [linux, windows, macos, sdist]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update rust toolchain
        run: rustup update
      - uses: actions/cache@v4
        id: cargo-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose
      - name: E2E test
        run: |
          cargo run --release -- setup --default
          cargo run --release -- -r
